// 12种小红书封面信息图风格定义
// 每种风格有独特的配色、字体风格和布局特征

export interface CoverStyle {
  id: string
  name: string
  // 背景
  bgColor: string
  bgPattern?: string
  // 标题区
  titleColor: string
  titleBg: string
  subtitleColor: string
  // 主图区装饰
  heroBg: string
  heroAccent: string
  // 左侧信息块
  leftBlock1Bg: string
  leftBlock1Border: string
  leftBlock1Title: string
  leftBlock2Bg: string
  leftBlock2Border: string
  leftBlock2Title: string
  // 右侧卖点区
  rightBg: string
  rightBorder: string
  rightTitleColor: string
  layerColors: string[]
  techBg: string
  techText: string
  productBg: string
  productText: string
  // 对比表格
  tableHeaderBg: string
  tableHeaderText: string
  tableBeforeBg: string
  tableAfterBg: string
  tableAfterText: string
  // 底部
  footerColor: string
  // 装饰元素颜色
  decorColor: string
  // 整体风格描述
  description: string
}

export const COVER_STYLES: CoverStyle[] = [
  // 风格1：原版草本绿（参考图风格）
  {
    id: 'herbal-classic',
    name: '草本经典',
    bgColor: '#F5F0E8',
    titleColor: '#1E4D2B',
    titleBg: 'transparent',
    subtitleColor: '#5C4A32',
    heroBg: '#EDE8DC',
    heroAccent: '#2D7A4F',
    leftBlock1Bg: '#E8F4EF',
    leftBlock1Border: '#7BC4A0',
    leftBlock1Title: '#1E4D2B',
    leftBlock2Bg: '#FFF3E0',
    leftBlock2Border: '#F0A030',
    leftBlock2Title: '#8B5E00',
    rightBg: '#FAFAF5',
    rightBorder: '#C8BFA8',
    rightTitleColor: '#1E4D2B',
    layerColors: ['#4CAF50', '#FFA726', '#42A5F5'],
    techBg: '#E8F5E9',
    techText: '#2E7D32',
    productBg: '#8B5E00',
    productText: '#FFFFFF',
    tableHeaderBg: '#F5F0E8',
    tableHeaderText: '#5C4A32',
    tableBeforeBg: '#FFF3E0',
    tableAfterBg: '#E8F4EF',
    tableAfterText: '#1E4D2B',
    footerColor: '#8B7355',
    decorColor: '#C8BFA8',
    description: '奶油米白背景，深绿主色，草本自然风',
  },
  // 风格2：清新薄荷
  {
    id: 'mint-fresh',
    name: '清新薄荷',
    bgColor: '#F0FAF6',
    titleColor: '#0D5C3A',
    titleBg: 'transparent',
    subtitleColor: '#2E7D5A',
    heroBg: '#E0F5EC',
    heroAccent: '#00A86B',
    leftBlock1Bg: '#D4F0E4',
    leftBlock1Border: '#00C47A',
    leftBlock1Title: '#005C35',
    leftBlock2Bg: '#FFF8E7',
    leftBlock2Border: '#FFB300',
    leftBlock2Title: '#7A5000',
    rightBg: '#F5FDF9',
    rightBorder: '#A8DFC4',
    rightTitleColor: '#005C35',
    layerColors: ['#00C47A', '#FFB300', '#00B0D8'],
    techBg: '#D4F0E4',
    techText: '#005C35',
    productBg: '#00A86B',
    productText: '#FFFFFF',
    tableHeaderBg: '#E0F5EC',
    tableHeaderText: '#005C35',
    tableBeforeBg: '#FFF8E7',
    tableAfterBg: '#D4F0E4',
    tableAfterText: '#005C35',
    footerColor: '#4A9A72',
    decorColor: '#A8DFC4',
    description: '清新薄荷绿，活力健康感',
  },
  // 风格3：暖橙琥珀
  {
    id: 'amber-warm',
    name: '暖橙琥珀',
    bgColor: '#FFF8F0',
    titleColor: '#8B3A00',
    titleBg: 'transparent',
    subtitleColor: '#A0522D',
    heroBg: '#FFE8D0',
    heroAccent: '#E07020',
    leftBlock1Bg: '#FFF0E0',
    leftBlock1Border: '#E07020',
    leftBlock1Title: '#8B3A00',
    leftBlock2Bg: '#E8F4EF',
    leftBlock2Border: '#4CAF50',
    leftBlock2Title: '#1E4D2B',
    rightBg: '#FFFAF5',
    rightBorder: '#E8C8A0',
    rightTitleColor: '#8B3A00',
    layerColors: ['#E07020', '#4CAF50', '#E91E63'],
    techBg: '#FFE8D0',
    techText: '#8B3A00',
    productBg: '#E07020',
    productText: '#FFFFFF',
    tableHeaderBg: '#FFE8D0',
    tableHeaderText: '#8B3A00',
    tableBeforeBg: '#FFF0E0',
    tableAfterBg: '#E8F4EF',
    tableAfterText: '#1E4D2B',
    footerColor: '#A0522D',
    decorColor: '#E8C8A0',
    description: '暖橙琥珀色调，温润养生感',
  },
  // 风格4：深夜蓝紫
  {
    id: 'midnight-blue',
    name: '深夜蓝紫',
    bgColor: '#F0F2FF',
    titleColor: '#1A237E',
    titleBg: 'transparent',
    subtitleColor: '#3949AB',
    heroBg: '#E3E8FF',
    heroAccent: '#3F51B5',
    leftBlock1Bg: '#E8EAF6',
    leftBlock1Border: '#5C6BC0',
    leftBlock1Title: '#1A237E',
    leftBlock2Bg: '#F3E5F5',
    leftBlock2Border: '#AB47BC',
    leftBlock2Title: '#6A1B9A',
    rightBg: '#F5F6FF',
    rightBorder: '#B0BEC5',
    rightTitleColor: '#1A237E',
    layerColors: ['#5C6BC0', '#AB47BC', '#26C6DA'],
    techBg: '#E8EAF6',
    techText: '#1A237E',
    productBg: '#3F51B5',
    productText: '#FFFFFF',
    tableHeaderBg: '#E3E8FF',
    tableHeaderText: '#1A237E',
    tableBeforeBg: '#F3E5F5',
    tableAfterBg: '#E8EAF6',
    tableAfterText: '#1A237E',
    footerColor: '#5C6BC0',
    decorColor: '#B0BEC5',
    description: '深夜蓝紫，适合熬夜/职场人群',
  },
  // 风格5：玫瑰粉红
  {
    id: 'rose-pink',
    name: '玫瑰粉红',
    bgColor: '#FFF5F8',
    titleColor: '#880E4F',
    titleBg: 'transparent',
    subtitleColor: '#C2185B',
    heroBg: '#FFE4EE',
    heroAccent: '#E91E63',
    leftBlock1Bg: '#FCE4EC',
    leftBlock1Border: '#F06292',
    leftBlock1Title: '#880E4F',
    leftBlock2Bg: '#F3E5F5',
    leftBlock2Border: '#CE93D8',
    leftBlock2Title: '#6A1B9A',
    rightBg: '#FFF8FB',
    rightBorder: '#F8BBD9',
    rightTitleColor: '#880E4F',
    layerColors: ['#E91E63', '#CE93D8', '#FF8A65'],
    techBg: '#FCE4EC',
    techText: '#880E4F',
    productBg: '#E91E63',
    productText: '#FFFFFF',
    tableHeaderBg: '#FFE4EE',
    tableHeaderText: '#880E4F',
    tableBeforeBg: '#F3E5F5',
    tableAfterBg: '#FCE4EC',
    tableAfterText: '#880E4F',
    footerColor: '#C2185B',
    decorColor: '#F8BBD9',
    description: '玫瑰粉红，适合女性/妈妈群体',
  },
  // 风格6：古风茶褐
  {
    id: 'tea-brown',
    name: '古风茶褐',
    bgColor: '#FAF5EC',
    titleColor: '#4A3728',
    titleBg: 'transparent',
    subtitleColor: '#6D4C41',
    heroBg: '#F0E6D8',
    heroAccent: '#795548',
    leftBlock1Bg: '#EFE8DC',
    leftBlock1Border: '#A1887F',
    leftBlock1Title: '#4A3728',
    leftBlock2Bg: '#F5F0E8',
    leftBlock2Border: '#BCAAA4',
    leftBlock2Title: '#5D4037',
    rightBg: '#FAF7F2',
    rightBorder: '#D7CCC8',
    rightTitleColor: '#4A3728',
    layerColors: ['#795548', '#A1887F', '#8D6E63'],
    techBg: '#EFE8DC',
    techText: '#4A3728',
    productBg: '#6D4C41',
    productText: '#FFFFFF',
    tableHeaderBg: '#F0E6D8',
    tableHeaderText: '#4A3728',
    tableBeforeBg: '#F5F0E8',
    tableAfterBg: '#EFE8DC',
    tableAfterText: '#4A3728',
    footerColor: '#8D6E63',
    decorColor: '#D7CCC8',
    description: '古风茶褐，传统中医养生感',
  },
  // 风格7：活力橙绿
  {
    id: 'vibrant-orange',
    name: '活力橙绿',
    bgColor: '#FFFDE7',
    titleColor: '#E65100',
    titleBg: 'transparent',
    subtitleColor: '#BF360C',
    heroBg: '#FFF3E0',
    heroAccent: '#FF6D00',
    leftBlock1Bg: '#FFF3E0',
    leftBlock1Border: '#FF6D00',
    leftBlock1Title: '#E65100',
    leftBlock2Bg: '#E8F5E9',
    leftBlock2Border: '#43A047',
    leftBlock2Title: '#1B5E20',
    rightBg: '#FFFFF5',
    rightBorder: '#FFE082',
    rightTitleColor: '#E65100',
    layerColors: ['#FF6D00', '#43A047', '#00ACC1'],
    techBg: '#FFF3E0',
    techText: '#E65100',
    productBg: '#FF6D00',
    productText: '#FFFFFF',
    tableHeaderBg: '#FFF3E0',
    tableHeaderText: '#E65100',
    tableBeforeBg: '#FFFDE7',
    tableAfterBg: '#E8F5E9',
    tableAfterText: '#1B5E20',
    footerColor: '#BF360C',
    decorColor: '#FFE082',
    description: '活力橙绿，运动/学生群体',
  },
  // 风格8：高冷灰白
  {
    id: 'cool-gray',
    name: '高冷灰白',
    bgColor: '#FAFAFA',
    titleColor: '#212121',
    titleBg: 'transparent',
    subtitleColor: '#424242',
    heroBg: '#F5F5F5',
    heroAccent: '#616161',
    leftBlock1Bg: '#EEEEEE',
    leftBlock1Border: '#9E9E9E',
    leftBlock1Title: '#212121',
    leftBlock2Bg: '#E8F5E9',
    leftBlock2Border: '#66BB6A',
    leftBlock2Title: '#1B5E20',
    rightBg: '#FFFFFF',
    rightBorder: '#E0E0E0',
    rightTitleColor: '#212121',
    layerColors: ['#616161', '#66BB6A', '#42A5F5'],
    techBg: '#EEEEEE',
    techText: '#212121',
    productBg: '#424242',
    productText: '#FFFFFF',
    tableHeaderBg: '#F5F5F5',
    tableHeaderText: '#212121',
    tableBeforeBg: '#EEEEEE',
    tableAfterBg: '#E8F5E9',
    tableAfterText: '#1B5E20',
    footerColor: '#757575',
    decorColor: '#E0E0E0',
    description: '高冷灰白，商务/高端人群',
  },
  // 风格9：森林深绿
  {
    id: 'forest-deep',
    name: '森林深绿',
    bgColor: '#F1F8F4',
    titleColor: '#1B4332',
    titleBg: 'transparent',
    subtitleColor: '#2D6A4F',
    heroBg: '#D8F3DC',
    heroAccent: '#40916C',
    leftBlock1Bg: '#D8F3DC',
    leftBlock1Border: '#52B788',
    leftBlock1Title: '#1B4332',
    leftBlock2Bg: '#FFF9C4',
    leftBlock2Border: '#F9A825',
    leftBlock2Title: '#7A5000',
    rightBg: '#F8FDF9',
    rightBorder: '#95D5B2',
    rightTitleColor: '#1B4332',
    layerColors: ['#40916C', '#74C69D', '#52B788'],
    techBg: '#D8F3DC',
    techText: '#1B4332',
    productBg: '#2D6A4F',
    productText: '#FFFFFF',
    tableHeaderBg: '#D8F3DC',
    tableHeaderText: '#1B4332',
    tableBeforeBg: '#FFF9C4',
    tableAfterBg: '#D8F3DC',
    tableAfterText: '#1B4332',
    footerColor: '#52B788',
    decorColor: '#95D5B2',
    description: '森林深绿，自然有机感',
  },
  // 风格10：珊瑚红橙
  {
    id: 'coral-red',
    name: '珊瑚红橙',
    bgColor: '#FFF5F3',
    titleColor: '#B71C1C',
    titleBg: 'transparent',
    subtitleColor: '#C62828',
    heroBg: '#FFEBEE',
    heroAccent: '#EF5350',
    leftBlock1Bg: '#FFEBEE',
    leftBlock1Border: '#EF5350',
    leftBlock1Title: '#B71C1C',
    leftBlock2Bg: '#FFF3E0',
    leftBlock2Border: '#FFA726',
    leftBlock2Title: '#7A4000',
    rightBg: '#FFF8F7',
    rightBorder: '#FFCDD2',
    rightTitleColor: '#B71C1C',
    layerColors: ['#EF5350', '#FFA726', '#66BB6A'],
    techBg: '#FFEBEE',
    techText: '#B71C1C',
    productBg: '#EF5350',
    productText: '#FFFFFF',
    tableHeaderBg: '#FFEBEE',
    tableHeaderText: '#B71C1C',
    tableBeforeBg: '#FFF3E0',
    tableAfterBg: '#FFEBEE',
    tableAfterText: '#B71C1C',
    footerColor: '#C62828',
    decorColor: '#FFCDD2',
    description: '珊瑚红橙，热情活力感',
  },
  // 风格11：天空蓝白
  {
    id: 'sky-blue',
    name: '天空蓝白',
    bgColor: '#F0F8FF',
    titleColor: '#0D47A1',
    titleBg: 'transparent',
    subtitleColor: '#1565C0',
    heroBg: '#E3F2FD',
    heroAccent: '#1E88E5',
    leftBlock1Bg: '#E3F2FD',
    leftBlock1Border: '#42A5F5',
    leftBlock1Title: '#0D47A1',
    leftBlock2Bg: '#E8F5E9',
    leftBlock2Border: '#66BB6A',
    leftBlock2Title: '#1B5E20',
    rightBg: '#F5FBFF',
    rightBorder: '#BBDEFB',
    rightTitleColor: '#0D47A1',
    layerColors: ['#1E88E5', '#66BB6A', '#FFA726'],
    techBg: '#E3F2FD',
    techText: '#0D47A1',
    productBg: '#1565C0',
    productText: '#FFFFFF',
    tableHeaderBg: '#E3F2FD',
    tableHeaderText: '#0D47A1',
    tableBeforeBg: '#E8F5E9',
    tableAfterBg: '#E3F2FD',
    tableAfterText: '#0D47A1',
    footerColor: '#1E88E5',
    decorColor: '#BBDEFB',
    description: '天空蓝白，清爽科技感',
  },
  // 风格12：紫金奢华
  {
    id: 'purple-gold',
    name: '紫金奢华',
    bgColor: '#FAF5FF',
    titleColor: '#4A148C',
    titleBg: 'transparent',
    subtitleColor: '#6A1B9A',
    heroBg: '#F3E5F5',
    heroAccent: '#7B1FA2',
    leftBlock1Bg: '#F3E5F5',
    leftBlock1Border: '#AB47BC',
    leftBlock1Title: '#4A148C',
    leftBlock2Bg: '#FFF8E1',
    leftBlock2Border: '#FFD54F',
    leftBlock2Title: '#7A5000',
    rightBg: '#FDFAFF',
    rightBorder: '#E1BEE7',
    rightTitleColor: '#4A148C',
    layerColors: ['#7B1FA2', '#FFD54F', '#EF5350'],
    techBg: '#F3E5F5',
    techText: '#4A148C',
    productBg: '#7B1FA2',
    productText: '#FFFFFF',
    tableHeaderBg: '#F3E5F5',
    tableHeaderText: '#4A148C',
    tableBeforeBg: '#FFF8E1',
    tableAfterBg: '#F3E5F5',
    tableAfterText: '#4A148C',
    footerColor: '#AB47BC',
    decorColor: '#E1BEE7',
    description: '紫金奢华，高端礼品感',
  },
]

// 根据种子随机选择风格（保证同一内容每次生成相同风格）
export function getStyleBySeed(seed: string): CoverStyle {
  let hash = 0
  for (let i = 0; i < seed.length; i++) {
    hash = ((hash << 5) - hash) + seed.charCodeAt(i)
    hash |= 0
  }
  const index = Math.abs(hash) % COVER_STYLES.length
  return COVER_STYLES[index]
}

// 完全随机选择风格
export function getRandomStyle(): CoverStyle {
  return COVER_STYLES[Math.floor(Math.random() * COVER_STYLES.length)]
}
