/**
 * 灵芝水铺 — 测试数据种子脚本
 * 写入：8款产品（作为 Prompt 记录）+ 50个客户（含6张关联表）+ 30条模拟素材
 *
 * 运行方式：npx tsx scripts/seed-test-data.ts
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─────────────────────────────────────────────
// 1. 产品数据（存入 Prompt 表，category = "product"）
// ─────────────────────────────────────────────
const PRODUCTS = [
  {
    key: "product_tea_qingzhi",
    name: "清脂纤纤草本定制茶饮",
    description: "健脾排湿，回元通络 — 适合湿气重、注重身材管理的年轻女性",
    content: JSON.stringify({
      type: "tea",
      tcmFunction: "健脾排湿，回元通络",
      targetAudience: "湿气重、注重身材管理的年轻女性",
      keyIngredients: ["灵芝液", "荷叶", "山楂", "薏苡仁", "茯苓"],
      slogan: "像喝水一样简单，轻盈每一天",
      complianceNote: "药食同源固体饮料，助力湿气调理，非医疗用途",
    }),
    category: "product",
  },
  {
    key: "product_tea_buqi",
    name: "补气焕活草本定制茶饮",
    description: "助阳培元，滋阴益肾 — 适合熬夜、压力大、精力不足的白领创业者",
    content: JSON.stringify({
      type: "tea",
      tcmFunction: "助阳培元，滋阴益肾",
      targetAudience: "熬夜、压力大、精力不足的白领创业者",
      keyIngredients: ["灵芝液", "黄芪", "枸杞", "红枣", "党参"],
      slogan: "元气满满，从一杯开始",
      complianceNote: "药食同源固体饮料，助力元气调理，非医疗用途",
    }),
    category: "product",
  },
  {
    key: "product_tea_shiqing",
    name: "湿祛轻畅草本定制茶饮",
    description: "行气畅达，化湿降脂 — 适合久坐不动、循环不畅的办公室人群",
    content: JSON.stringify({
      type: "tea",
      tcmFunction: "行气畅达，化湿降脂",
      targetAudience: "久坐不动、循环不畅的办公室人群",
      keyIngredients: ["灵芝液", "陈皮", "赤小豆", "冬瓜皮", "泽泻"],
      slogan: "告别沉重感，轻盈每一步",
      complianceNote: "药食同源固体饮料，助力湿气调理，非医疗用途",
    }),
    category: "product",
  },
  {
    key: "product_tea_hongyan",
    name: "红颜透润草本定制茶饮",
    description: "益气活血，养颜生肌 — 适合注重皮肤保养、气血不足的爱美女性",
    content: JSON.stringify({
      type: "tea",
      tcmFunction: "益气活血，养颜生肌",
      targetAudience: "注重皮肤保养、气血不足的爱美女性",
      keyIngredients: ["灵芝液", "玫瑰花", "桃花", "当归", "红花"],
      slogan: "由内而外的透亮，气血足才是真美",
      complianceNote: "药食同源固体饮料，助力气血调理，非医疗用途",
    }),
    category: "product",
  },
  {
    key: "product_coffee_yuexian",
    name: "悦纤草本美式",
    description: "健脾排湿+提神醒脑 — 适合关注湿气管理的白领及健身爱好者",
    content: JSON.stringify({
      type: "coffee",
      tcmFunction: "健脾排湿，提神醒脑",
      targetAudience: "关注湿气管理的白领及健身爱好者",
      keyIngredients: ["灵芝液", "精品咖啡豆", "荷叶提取物", "薏苡仁"],
      slogan: "咖啡因+草本双重加持，清爽一整天",
      complianceNote: "药食同源固体饮料，助力湿气调理，非医疗用途",
    }),
    category: "product",
  },
  {
    key: "product_coffee_yuehuo",
    name: "悦活草本美式",
    description: "助阳培元+提神醒脑 — 适合高强度脑力劳动者、需长时间保持专注的奋斗者",
    content: JSON.stringify({
      type: "coffee",
      tcmFunction: "助阳培元，提神醒脑",
      targetAudience: "高强度脑力劳动者、需长时间保持专注的奋斗者",
      keyIngredients: ["灵芝液", "精品咖啡豆", "黄芪提取物", "枸杞"],
      slogan: "打工人的续命神器，比普通美式健康多了",
      complianceNote: "药食同源固体饮料，助力元气调理，非医疗用途",
    }),
    category: "product",
  },
  {
    key: "product_coffee_yueqing",
    name: "悦轻草本美式",
    description: "行气畅达+提神醒脑 — 适合身体沉重、循环不畅的都市人群",
    content: JSON.stringify({
      type: "coffee",
      tcmFunction: "行气畅达，提神醒脑",
      targetAudience: "身体沉重、循环不畅的都市人群",
      keyIngredients: ["灵芝液", "精品咖啡豆", "陈皮提取物", "赤小豆"],
      slogan: "轻盈感从早晨第一杯开始",
      complianceNote: "药食同源固体饮料，助力气机调理，非医疗用途",
    }),
    category: "product",
  },
  {
    key: "product_coffee_yueyan",
    name: "悦颜草本美式",
    description: "益气活血+提神醒脑 — 适合追求效率与颜值并存的职场女性",
    content: JSON.stringify({
      type: "coffee",
      tcmFunction: "益气活血，提神醒脑",
      targetAudience: "追求效率与颜值并存的职场女性",
      keyIngredients: ["灵芝液", "精品咖啡豆", "玫瑰提取物", "当归"],
      slogan: "颜值与效率，一杯全拿下",
      complianceNote: "药食同源固体饮料，助力气血调理，非医疗用途",
    }),
    category: "product",
  },
];

// ─────────────────────────────────────────────
// 2. 客户数据（5类人群 × 10人）
// ─────────────────────────────────────────────

// 都市白领（10人）
const CUSTOMERS_BAILING = [
  {
    name: "林晓雯",
    nickname: "晓雯在打工",
    gender: "female",
    age: 28,
    occupation: "互联网产品经理",
    city: "上海",
    income: "15k-25k",
    category: "都市白领",
    lifestyle: "朝九晚十，周末健身，偶尔下厨",
    painPoints: "长期熬夜导致气色差，精力不足，下午容易犯困",
    needs: "提神醒脑同时不伤身，兼顾养生",
    scenes: "办公室下午茶、加班续命、健身前后",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "xiaohongshu",
    personaName: "都市白领_产品经理",
    targetAudience: "25-35岁互联网从业者",
    preferredProducts: ["悦活草本美式", "补气焕活草本定制茶饮"],
    catchphrases: ["打工人续命神器", "比星巴克健康多了", "熬夜必备"],
    timeSlots: ["08:00-09:00", "14:00-15:00", "21:00-22:00"],
    xhsRatio: 0.7,
  },
  {
    name: "张宇航",
    nickname: "宇航不加班",
    gender: "male",
    age: 32,
    occupation: "金融分析师",
    city: "北京",
    income: "25k-40k",
    category: "都市白领",
    lifestyle: "高强度工作，注重效率，偶尔健身",
    painPoints: "脑力消耗大，记忆力下降，睡眠质量差",
    needs: "提升专注力，改善睡眠，补充元气",
    scenes: "早晨通勤、会议前、深夜加班",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "xiaohongshu",
    personaName: "都市白领_金融从业者",
    targetAudience: "28-38岁金融从业者",
    preferredProducts: ["悦活草本美式", "补气焕活草本定制茶饮"],
    catchphrases: ["高效工作的秘密", "脑力劳动者必备", "专注力UP"],
    timeSlots: ["07:30-08:30", "12:00-13:00", "22:00-23:00"],
    xhsRatio: 0.7,
  },
  {
    name: "陈思琪",
    nickname: "思琪爱养生",
    gender: "female",
    age: 26,
    occupation: "UI设计师",
    city: "深圳",
    income: "10k-18k",
    category: "都市白领",
    lifestyle: "久坐办公，喜欢下班后散步，关注健康",
    painPoints: "久坐腰酸，下午精力下滑，皮肤状态不好",
    needs: "改善循环，提升气色，温和养生",
    scenes: "办公室下午茶、下班后放松",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "xiaohongshu",
    personaName: "都市白领_设计师",
    targetAudience: "22-30岁创意从业者",
    preferredProducts: ["悦颜草本美式", "红颜透润草本定制茶饮"],
    catchphrases: ["设计师的续命水", "久坐党必备", "气色管理"],
    timeSlots: ["09:00-10:00", "15:00-16:00", "20:00-21:00"],
    xhsRatio: 0.75,
  },
  {
    name: "王浩然",
    nickname: "浩然在创业",
    gender: "male",
    age: 35,
    occupation: "创业公司CEO",
    city: "杭州",
    income: "40k+",
    category: "都市白领",
    lifestyle: "全天候工作，出差频繁，注重效率",
    painPoints: "压力极大，睡眠不足，免疫力下降",
    needs: "快速补充元气，提升抗压能力",
    scenes: "早晨出发前、商务会议、出差途中",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "xiaohongshu",
    personaName: "都市白领_创业者",
    targetAudience: "30-40岁创业者",
    preferredProducts: ["悦活草本美式", "补气焕活草本定制茶饮"],
    catchphrases: ["创业者的能量站", "高效养生", "时间就是金钱"],
    timeSlots: ["06:30-07:30", "11:30-12:30", "23:00-24:00"],
    xhsRatio: 0.6,
  },
  {
    name: "刘梦瑶",
    nickname: "梦瑶爱喝茶",
    gender: "female",
    age: 29,
    occupation: "市场营销主管",
    city: "广州",
    income: "15k-22k",
    category: "都市白领",
    lifestyle: "社交活跃，喜欢尝试新事物，注重生活品质",
    painPoints: "应酬多，作息不规律，气血不足",
    needs: "调理气血，改善疲劳感",
    scenes: "下午茶时间、聚会分享、日常打卡",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "xiaohongshu",
    personaName: "都市白领_营销人",
    targetAudience: "25-35岁营销从业者",
    preferredProducts: ["悦颜草本美式", "红颜透润草本定制茶饮"],
    catchphrases: ["营销人的秘密武器", "气血好才能拼", "颜值管理"],
    timeSlots: ["10:00-11:00", "15:00-16:00", "21:30-22:30"],
    xhsRatio: 0.7,
  },
  {
    name: "赵子轩",
    nickname: "子轩不熬夜",
    gender: "male",
    age: 27,
    occupation: "软件工程师",
    city: "成都",
    income: "12k-20k",
    category: "都市白领",
    lifestyle: "程序员生活，喜欢打游戏，偶尔健身",
    painPoints: "熬夜成习惯，眼睛疲劳，精力透支",
    needs: "护眼养肝，提升精力，改善睡眠",
    scenes: "深夜码代码、午休、周末放松",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "xiaohongshu",
    personaName: "都市白领_程序员",
    targetAudience: "22-32岁技术从业者",
    preferredProducts: ["悦活草本美式", "补气焕活草本定制茶饮"],
    catchphrases: ["程序员的肝脏保护神", "熬夜党必备", "代码+养生"],
    timeSlots: ["10:00-11:00", "14:00-15:00", "23:00-24:00"],
    xhsRatio: 0.65,
  },
  {
    name: "孙雨欣",
    nickname: "雨欣在养生",
    gender: "female",
    age: 31,
    occupation: "律师",
    city: "北京",
    income: "30k-50k",
    category: "都市白领",
    lifestyle: "高压工作，注重细节，追求品质生活",
    painPoints: "长期高压，肠胃不适，气色暗沉",
    needs: "舒缓压力，调理肠胃，改善气色",
    scenes: "早晨上班前、庭审间隙、晚间放松",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "xiaohongshu",
    personaName: "都市白领_法律从业者",
    targetAudience: "28-38岁高知职业女性",
    preferredProducts: ["悦颜草本美式", "红颜透润草本定制茶饮"],
    catchphrases: ["高压工作者的调节器", "精致生活必备", "内外兼修"],
    timeSlots: ["07:00-08:00", "12:30-13:30", "21:00-22:00"],
    xhsRatio: 0.7,
  },
  {
    name: "周明杰",
    nickname: "明杰爱健康",
    gender: "male",
    age: 33,
    occupation: "销售总监",
    city: "上海",
    income: "25k-45k",
    category: "都市白领",
    lifestyle: "出差多，应酬多，注重形象管理",
    painPoints: "应酬伤身，精力消耗大，需要快速恢复",
    needs: "快速补充元气，维持良好状态",
    scenes: "出差途中、商务餐后、早晨出发",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "wechat",
    personaName: "都市白领_销售精英",
    targetAudience: "28-40岁销售管理层",
    preferredProducts: ["悦活草本美式", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["销售精英的能量补给", "应酬后的修复神器", "状态满满"],
    timeSlots: ["07:00-08:00", "13:00-14:00", "22:00-23:00"],
    xhsRatio: 0.3,
  },
  {
    name: "吴晓彤",
    nickname: "晓彤的养生日记",
    gender: "female",
    age: 25,
    occupation: "新媒体运营",
    city: "深圳",
    income: "8k-15k",
    category: "都市白领",
    lifestyle: "内容创作者，关注流行趋势，喜欢分享",
    painPoints: "长时间盯屏幕，颈椎不适，精力不稳定",
    needs: "护眼，改善颈部循环，稳定精力",
    scenes: "内容创作时、直播前、日常打卡",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "xiaohongshu",
    personaName: "都市白领_新媒体人",
    targetAudience: "20-28岁内容创作者",
    preferredProducts: ["悦活草本美式", "补气焕活草本定制茶饮"],
    catchphrases: ["内容人的续命水", "创作力MAX", "今日打卡"],
    timeSlots: ["09:00-10:00", "16:00-17:00", "22:00-23:00"],
    xhsRatio: 0.8,
  },
  {
    name: "郑建国",
    nickname: "建国养生中",
    gender: "male",
    age: 38,
    occupation: "项目经理",
    city: "武汉",
    income: "18k-28k",
    category: "都市白领",
    lifestyle: "项目压力大，经常加班，关注健康",
    painPoints: "长期压力导致脱发，睡眠质量差，精力不足",
    needs: "减压，改善睡眠，补充元气",
    scenes: "项目冲刺期、深夜加班、周末恢复",
    language: "打工人续命神器，比星巴克健康多了",
    platform: "wechat",
    personaName: "都市白领_项目管理",
    targetAudience: "30-40岁项目管理人员",
    preferredProducts: ["补气焕活草本定制茶饮", "悦活草本美式"],
    catchphrases: ["项目经理的减压神器", "熬夜加班必备", "元气恢复"],
    timeSlots: ["08:00-09:00", "14:00-15:00", "23:00-24:00"],
    xhsRatio: 0.35,
  },
];

// 精致妈妈（10人）
const CUSTOMERS_MAMA = [
  {
    name: "李慧敏",
    nickname: "慧敏麻麻",
    gender: "female",
    age: 34,
    occupation: "全职妈妈",
    city: "上海",
    income: "家庭收入30k+",
    category: "精致妈妈",
    lifestyle: "照顾孩子，注重家庭健康，喜欢分享育儿经验",
    painPoints: "产后气血不足，皮肤状态下滑，精力不够",
    needs: "调理气血，恢复活力，兼顾家庭",
    scenes: "送孩子上学后、午间休息、晚间护肤",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "wechat",
    personaName: "精致妈妈_全职",
    targetAudience: "30-40岁全职妈妈",
    preferredProducts: ["红颜透润草本定制茶饮", "悦颜草本美式"],
    catchphrases: ["姐妹们", "亲测有效", "全家都爱喝"],
    timeSlots: ["09:30-10:30", "14:00-15:00", "21:00-22:00"],
    xhsRatio: 0.4,
  },
  {
    name: "王芳芳",
    nickname: "芳芳辣妈",
    gender: "female",
    age: 37,
    occupation: "兼职教师",
    city: "杭州",
    income: "家庭收入20k+",
    category: "精致妈妈",
    lifestyle: "工作家庭两不误，注重自我提升",
    painPoints: "工作家庭双重压力，容易疲惫，气色不佳",
    needs: "快速恢复精力，改善气色，高效养生",
    scenes: "课间休息、接孩子前、晚间放松",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "wechat",
    personaName: "精致妈妈_职场妈妈",
    targetAudience: "32-42岁职场妈妈",
    preferredProducts: ["红颜透润草本定制茶饮", "悦颜草本美式"],
    catchphrases: ["职场妈妈的秘密", "亲测有效", "姐妹们一起来"],
    timeSlots: ["10:00-11:00", "15:30-16:30", "21:30-22:30"],
    xhsRatio: 0.45,
  },
  {
    name: "张美玲",
    nickname: "美玲爱生活",
    gender: "female",
    age: 32,
    occupation: "电商创业",
    city: "广州",
    income: "20k-35k",
    category: "精致妈妈",
    lifestyle: "创业妈妈，注重效率，喜欢分享好物",
    painPoints: "创业压力大，睡眠不足，皮肤干燥",
    needs: "补水养颜，提升精力，调理内分泌",
    scenes: "早晨工作前、直播间、孩子睡后",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "xiaohongshu",
    personaName: "精致妈妈_创业妈妈",
    targetAudience: "28-38岁创业妈妈",
    preferredProducts: ["红颜透润草本定制茶饮", "悦颜草本美式"],
    catchphrases: ["创业妈妈的能量站", "姐妹们种草", "亲测好用"],
    timeSlots: ["08:30-09:30", "13:00-14:00", "22:00-23:00"],
    xhsRatio: 0.55,
  },
  {
    name: "陈雅婷",
    nickname: "雅婷的育儿日记",
    gender: "female",
    age: 30,
    occupation: "护士",
    city: "成都",
    income: "8k-15k",
    category: "精致妈妈",
    lifestyle: "医护工作者，注重科学养生，关注家人健康",
    painPoints: "上夜班导致作息紊乱，体力消耗大",
    needs: "调节作息，补充体力，科学养生",
    scenes: "下夜班后、孩子午睡时、家庭聚餐",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "wechat",
    personaName: "精致妈妈_医护妈妈",
    targetAudience: "26-36岁医护工作者妈妈",
    preferredProducts: ["补气焕活草本定制茶饮", "红颜透润草本定制茶饮"],
    catchphrases: ["医护人的养生选择", "科学调理", "全家健康"],
    timeSlots: ["08:00-09:00", "14:30-15:30", "20:00-21:00"],
    xhsRatio: 0.4,
  },
  {
    name: "刘晓燕",
    nickname: "晓燕妈咪",
    gender: "female",
    age: 39,
    occupation: "企业HR",
    city: "北京",
    income: "15k-25k",
    category: "精致妈妈",
    lifestyle: "职场妈妈，注重家庭氛围，喜欢烹饪",
    painPoints: "更年期前期症状，情绪波动，睡眠质量下降",
    needs: "稳定情绪，改善睡眠，调理内分泌",
    scenes: "早晨准备早餐时、午休、晚间护肤",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "wechat",
    personaName: "精致妈妈_HR妈妈",
    targetAudience: "35-45岁职场妈妈",
    preferredProducts: ["红颜透润草本定制茶饮", "补气焕活草本定制茶饮"],
    catchphrases: ["40岁女人的秘密", "姐妹们抱团养生", "亲测有效"],
    timeSlots: ["07:30-08:30", "12:00-13:00", "22:00-23:00"],
    xhsRatio: 0.4,
  },
  {
    name: "周静怡",
    nickname: "静怡和宝贝",
    gender: "female",
    age: 28,
    occupation: "平面设计师",
    city: "深圳",
    income: "10k-18k",
    category: "精致妈妈",
    lifestyle: "新手妈妈，注重育儿，喜欢记录生活",
    painPoints: "哺乳期营养消耗大，精力不足，脱发严重",
    needs: "补充营养，改善脱发，恢复体力",
    scenes: "哺乳间隙、宝宝午睡、晚间记录",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "xiaohongshu",
    personaName: "精致妈妈_新手妈妈",
    targetAudience: "24-32岁新手妈妈",
    preferredProducts: ["红颜透润草本定制茶饮", "补气焕活草本定制茶饮"],
    catchphrases: ["新手妈妈的养生日记", "宝宝健康妈妈美", "亲测有效"],
    timeSlots: ["10:00-11:00", "14:00-15:00", "21:00-22:00"],
    xhsRatio: 0.6,
  },
  {
    name: "吴丽华",
    nickname: "丽华的幸福生活",
    gender: "female",
    age: 42,
    occupation: "公务员",
    city: "南京",
    income: "10k-18k",
    category: "精致妈妈",
    lifestyle: "稳定生活，注重传统养生，喜欢分享",
    painPoints: "中年发福，代谢减慢，容易疲惫",
    needs: "控制体重，提升代谢，改善精力",
    scenes: "早晨散步后、午餐时、下班后",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "wechat",
    personaName: "精致妈妈_公务员妈妈",
    targetAudience: "38-48岁稳定职业妈妈",
    preferredProducts: ["清脂纤纤草本定制茶饮", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["中年养生不将就", "全家都爱喝", "亲测有效"],
    timeSlots: ["08:00-09:00", "12:30-13:30", "20:00-21:00"],
    xhsRatio: 0.35,
  },
  {
    name: "赵欣欣",
    nickname: "欣欣妈的好物分享",
    gender: "female",
    age: 35,
    occupation: "小学教师",
    city: "武汉",
    income: "8k-14k",
    category: "精致妈妈",
    lifestyle: "教师妈妈，注重孩子教育，关注家庭健康",
    painPoints: "用嗓过多，体力消耗大，免疫力下降",
    needs: "保护嗓子，增强免疫力，补充元气",
    scenes: "课间休息、放学后、周末家庭活动",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "wechat",
    personaName: "精致妈妈_教师妈妈",
    targetAudience: "30-40岁教师妈妈",
    preferredProducts: ["补气焕活草本定制茶饮", "红颜透润草本定制茶饮"],
    catchphrases: ["老师的养生秘诀", "全家都爱喝", "亲测好用"],
    timeSlots: ["09:30-10:30", "15:00-16:00", "21:00-22:00"],
    xhsRatio: 0.4,
  },
  {
    name: "孙婷婷",
    nickname: "婷婷辣妈日记",
    gender: "female",
    age: 33,
    occupation: "自由职业者",
    city: "杭州",
    income: "15k-30k",
    category: "精致妈妈",
    lifestyle: "自由职业，时间灵活，注重生活品质",
    painPoints: "作息不规律，皮肤状态波动，气血不稳",
    needs: "稳定气血，改善皮肤，调节作息",
    scenes: "早晨工作前、下午茶、晚间护肤",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "xiaohongshu",
    personaName: "精致妈妈_自由职业",
    targetAudience: "28-38岁自由职业妈妈",
    preferredProducts: ["红颜透润草本定制茶饮", "悦颜草本美式"],
    catchphrases: ["自由职业妈妈的日常", "姐妹们种草", "亲测有效"],
    timeSlots: ["09:00-10:00", "14:30-15:30", "22:00-23:00"],
    xhsRatio: 0.55,
  },
  {
    name: "钱小燕",
    nickname: "小燕子飞飞",
    gender: "female",
    age: 36,
    occupation: "会计",
    city: "苏州",
    income: "12k-20k",
    category: "精致妈妈",
    lifestyle: "稳定工作，注重家庭，喜欢烹饪养生",
    painPoints: "久坐导致腰背酸痛，眼睛疲劳，气血不足",
    needs: "缓解久坐不适，养眼护肝，补充气血",
    scenes: "午休时间、下班后、周末家庭时光",
    language: "姐妹们，亲测有效，全家都爱喝",
    platform: "wechat",
    personaName: "精致妈妈_会计妈妈",
    targetAudience: "30-40岁财务从业妈妈",
    preferredProducts: ["红颜透润草本定制茶饮", "补气焕活草本定制茶饮"],
    catchphrases: ["会计妈妈的养生日常", "全家都爱喝", "亲测有效"],
    timeSlots: ["12:00-13:00", "16:00-17:00", "21:30-22:30"],
    xhsRatio: 0.4,
  },
];

// 健康自律者（10人）
const CUSTOMERS_JIANKANG = [
  {
    name: "黄志强",
    nickname: "志强打卡中",
    gender: "male",
    age: 25,
    occupation: "健身教练",
    city: "上海",
    income: "10k-20k",
    category: "健康自律",
    lifestyle: "每天健身，严格饮食管理，记录身体数据",
    painPoints: "高强度训练后恢复慢，需要科学补充",
    needs: "促进恢复，助力减脂，科学养生",
    scenes: "训练前后、早晨打卡、客户分享",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_健身教练",
    targetAudience: "20-30岁健身爱好者",
    preferredProducts: ["清脂纤纤草本定制茶饮", "悦纤草本美式"],
    catchphrases: ["今日打卡", "坚持第N天", "掉秤了"],
    timeSlots: ["06:00-07:00", "12:00-13:00", "20:00-21:00"],
    xhsRatio: 0.85,
  },
  {
    name: "林思雨",
    nickname: "思雨的减脂日记",
    gender: "female",
    age: 23,
    occupation: "大学生",
    city: "北京",
    income: "生活费",
    category: "健康自律",
    lifestyle: "注重体重管理，坚持运动，记录饮食",
    painPoints: "减脂期间容易反弹，湿气重导致虚胖",
    needs: "排湿减脂，控制食欲，科学瘦身",
    scenes: "早晨空腹、运动后、睡前打卡",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_减脂学生",
    targetAudience: "18-25岁注重体重管理的学生",
    preferredProducts: ["清脂纤纤草本定制茶饮", "悦纤草本美式"],
    catchphrases: ["减脂打卡", "今天又瘦了一点", "坚持就是胜利"],
    timeSlots: ["07:00-08:00", "12:30-13:30", "22:00-23:00"],
    xhsRatio: 0.9,
  },
  {
    name: "陈浩宇",
    nickname: "浩宇健身日志",
    gender: "male",
    age: 29,
    occupation: "互联网工程师",
    city: "深圳",
    income: "18k-30k",
    category: "健康自律",
    lifestyle: "工作之余坚持健身，注重饮食搭配",
    painPoints: "久坐加健身，身体循环不畅，恢复慢",
    needs: "促进循环，加速恢复，维持体型",
    scenes: "健身房前后、午休、周末训练",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_健身工程师",
    targetAudience: "25-35岁健身爱好者",
    preferredProducts: ["湿祛轻畅草本定制茶饮", "悦纤草本美式"],
    catchphrases: ["健身打卡", "今日训练完成", "坚持第N天"],
    timeSlots: ["07:00-08:00", "18:00-19:00", "22:00-23:00"],
    xhsRatio: 0.8,
  },
  {
    name: "周雪梅",
    nickname: "雪梅的健康生活",
    gender: "female",
    age: 31,
    occupation: "瑜伽教练",
    city: "杭州",
    income: "8k-15k",
    category: "健康自律",
    lifestyle: "每天练习瑜伽，注重身心平衡，素食为主",
    painPoints: "素食导致气血偏弱，需要温和补充",
    needs: "温和补气血，调节内分泌，身心平衡",
    scenes: "晨练后、课间、冥想时",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_瑜伽教练",
    targetAudience: "25-35岁瑜伽爱好者",
    preferredProducts: ["红颜透润草本定制茶饮", "清脂纤纤草本定制茶饮"],
    catchphrases: ["今日瑜伽打卡", "身心平衡", "坚持健康生活"],
    timeSlots: ["06:30-07:30", "12:00-13:00", "20:30-21:30"],
    xhsRatio: 0.85,
  },
  {
    name: "王建明",
    nickname: "建明跑步中",
    gender: "male",
    age: 35,
    occupation: "销售经理",
    city: "成都",
    income: "15k-25k",
    category: "健康自律",
    lifestyle: "坚持跑步，参加马拉松，注重体能管理",
    painPoints: "长跑后关节不适，体力恢复慢",
    needs: "促进关节恢复，补充体力，提升耐力",
    scenes: "晨跑后、比赛前后、日常补给",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_跑步爱好者",
    targetAudience: "28-40岁跑步爱好者",
    preferredProducts: ["湿祛轻畅草本定制茶饮", "悦轻草本美式"],
    catchphrases: ["今日跑步打卡", "马拉松备赛中", "坚持第N天"],
    timeSlots: ["06:00-07:00", "12:00-13:00", "21:00-22:00"],
    xhsRatio: 0.75,
  },
  {
    name: "李婷婷",
    nickname: "婷婷的轻食日记",
    gender: "female",
    age: 27,
    occupation: "营养师",
    city: "广州",
    income: "8k-15k",
    category: "健康自律",
    lifestyle: "专业营养知识，严格饮食管理，分享健康生活",
    painPoints: "工作压力大，需要科学管理身体状态",
    needs: "科学补充，维持最佳状态，专业养生",
    scenes: "工作间隙、客户咨询前、日常打卡",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_营养师",
    targetAudience: "22-32岁健康意识强的年轻人",
    preferredProducts: ["清脂纤纤草本定制茶饮", "悦纤草本美式"],
    catchphrases: ["营养师的日常选择", "科学养生打卡", "今日健康达标"],
    timeSlots: ["08:00-09:00", "12:30-13:30", "21:00-22:00"],
    xhsRatio: 0.85,
  },
  {
    name: "张伟东",
    nickname: "伟东的体重管理",
    gender: "male",
    age: 40,
    occupation: "企业高管",
    city: "上海",
    income: "40k+",
    category: "健康自律",
    lifestyle: "高压工作，坚持健身，注重健康管理",
    painPoints: "中年发福，代谢下降，需要系统管理",
    needs: "提升代谢，控制体重，维持精力",
    scenes: "早晨健身后、商务餐前、日常管理",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_高管",
    targetAudience: "35-45岁注重健康的高管",
    preferredProducts: ["清脂纤纤草本定制茶饮", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["高管的健康管理", "坚持打卡", "体重管理进行中"],
    timeSlots: ["06:30-07:30", "12:00-13:00", "22:00-23:00"],
    xhsRatio: 0.7,
  },
  {
    name: "刘佳佳",
    nickname: "佳佳的健康打卡",
    gender: "female",
    age: 22,
    occupation: "大学生",
    city: "武汉",
    income: "生活费",
    category: "健康自律",
    lifestyle: "大学生，注重外表管理，坚持运动",
    painPoints: "学业压力大，作息不规律，皮肤状态差",
    needs: "改善皮肤，调节作息，减脂塑形",
    scenes: "早晨起床、课间、晚自习后",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_大学生",
    targetAudience: "18-24岁注重健康的大学生",
    preferredProducts: ["清脂纤纤草本定制茶饮", "悦纤草本美式"],
    catchphrases: ["大学生养生打卡", "今日健康达标", "坚持就是胜利"],
    timeSlots: ["08:00-09:00", "12:00-13:00", "22:30-23:30"],
    xhsRatio: 0.9,
  },
  {
    name: "吴志远",
    nickname: "志远的运动日记",
    gender: "male",
    age: 26,
    occupation: "体育老师",
    city: "南京",
    income: "7k-12k",
    category: "健康自律",
    lifestyle: "体育专业，每天运动，注重身体数据",
    painPoints: "高强度运动后肌肉酸痛，需要快速恢复",
    needs: "促进恢复，补充电解质，维持体能",
    scenes: "训练后、课间、比赛前后",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_体育老师",
    targetAudience: "22-32岁运动爱好者",
    preferredProducts: ["湿祛轻畅草本定制茶饮", "悦轻草本美式"],
    catchphrases: ["运动打卡", "今日训练完成", "体能持续提升"],
    timeSlots: ["06:00-07:00", "12:00-13:00", "19:00-20:00"],
    xhsRatio: 0.8,
  },
  {
    name: "赵晓丽",
    nickname: "晓丽减脂日记",
    gender: "female",
    age: 28,
    occupation: "会计",
    city: "苏州",
    income: "8k-15k",
    category: "健康自律",
    lifestyle: "上班族，业余时间坚持健身，记录减脂过程",
    painPoints: "久坐导致湿气重，下半身容易浮肿",
    needs: "排湿消肿，改善循环，辅助减脂",
    scenes: "早晨空腹、午休、健身后",
    language: "今日打卡，坚持第N天，掉秤了",
    platform: "xiaohongshu",
    personaName: "健康自律_上班族健身",
    targetAudience: "24-34岁注重体型的上班族",
    preferredProducts: ["清脂纤纤草本定制茶饮", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["减脂打卡第N天", "今天又瘦了", "坚持就是胜利"],
    timeSlots: ["07:00-08:00", "12:00-13:00", "21:30-22:30"],
    xhsRatio: 0.85,
  },
];

// 银发新青年（10人）
const CUSTOMERS_YINFA = [
  {
    name: "王德明",
    nickname: "老王的养生经",
    gender: "male",
    age: 62,
    occupation: "退休工程师",
    city: "北京",
    income: "退休金+积蓄",
    category: "银发新青年",
    lifestyle: "退休后注重养生，每天散步，关注健康资讯",
    painPoints: "关节不适，精力下降，睡眠质量差",
    needs: "改善关节，提升精力，改善睡眠",
    scenes: "早晨散步后、午后休息、晚间养生",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_退休工程师",
    targetAudience: "55-70岁退休男性",
    preferredProducts: ["补气焕活草本定制茶饮", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["老伴也说好", "确实感觉精神了", "喝了三个月了"],
    timeSlots: ["08:00-09:00", "14:00-15:00", "20:00-21:00"],
    xhsRatio: 0.2,
  },
  {
    name: "李秀英",
    nickname: "秀英阿姨的健康日记",
    gender: "female",
    age: 58,
    occupation: "退休教师",
    city: "上海",
    income: "退休金",
    category: "银发新青年",
    lifestyle: "退休后学习新技能，关注健康，喜欢分享",
    painPoints: "更年期不适，骨质疏松风险，气血不足",
    needs: "调理更年期症状，补充钙质，改善气血",
    scenes: "早晨太极后、午后茶时、晚间散步",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_退休教师",
    targetAudience: "50-65岁退休女性",
    preferredProducts: ["红颜透润草本定制茶饮", "补气焕活草本定制茶饮"],
    catchphrases: ["老姐妹们推荐", "确实感觉好多了", "坚持喝了两个月"],
    timeSlots: ["08:30-09:30", "14:30-15:30", "20:30-21:30"],
    xhsRatio: 0.25,
  },
  {
    name: "张国华",
    nickname: "国华叔的养生之道",
    gender: "male",
    age: 55,
    occupation: "企业顾问",
    city: "广州",
    income: "顾问费+退休金",
    category: "银发新青年",
    lifestyle: "半退休状态，注重养生，喜欢分享经验",
    painPoints: "高血压风险，代谢减慢，精力不如从前",
    needs: "辅助控压，提升代谢，维持活力",
    scenes: "早晨锻炼后、商务会面、下午茶",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_企业顾问",
    targetAudience: "50-60岁半退休专业人士",
    preferredProducts: ["湿祛轻畅草本定制茶饮", "补气焕活草本定制茶饮"],
    catchphrases: ["过来人的经验", "确实感觉精神了", "老伴也爱喝"],
    timeSlots: ["07:30-08:30", "14:00-15:00", "20:00-21:00"],
    xhsRatio: 0.2,
  },
  {
    name: "陈桂芳",
    nickname: "桂芳奶奶的秘方",
    gender: "female",
    age: 65,
    occupation: "退休医生",
    city: "成都",
    income: "退休金",
    category: "银发新青年",
    lifestyle: "退休医生，科学养生，关注家人健康",
    painPoints: "年龄增长导致各项机能下降，需要全面调理",
    needs: "全面调理，科学养生，延缓衰老",
    scenes: "早晨锻炼、家庭聚餐、社区活动",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_退休医生",
    targetAudience: "60-70岁退休医疗工作者",
    preferredProducts: ["补气焕活草本定制茶饮", "红颜透润草本定制茶饮"],
    catchphrases: ["医生的养生选择", "科学调理", "全家都在喝"],
    timeSlots: ["08:00-09:00", "14:00-15:00", "19:30-20:30"],
    xhsRatio: 0.2,
  },
  {
    name: "刘志刚",
    nickname: "志刚大叔",
    gender: "male",
    age: 52,
    occupation: "工厂管理层",
    city: "武汉",
    income: "15k-20k",
    category: "银发新青年",
    lifestyle: "工作压力大，注重实用养生，不追求花哨",
    painPoints: "腰背酸痛，体力下降，睡眠不好",
    needs: "缓解腰背不适，恢复体力，改善睡眠",
    scenes: "工作间隙、下班后、周末休息",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_工厂管理",
    targetAudience: "48-58岁工厂管理人员",
    preferredProducts: ["补气焕活草本定制茶饮", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["实用养生不花哨", "老伴也说好", "确实有效果"],
    timeSlots: ["09:00-10:00", "15:00-16:00", "21:00-22:00"],
    xhsRatio: 0.15,
  },
  {
    name: "周淑华",
    nickname: "淑华阿姨爱养生",
    gender: "female",
    age: 60,
    occupation: "退休会计",
    city: "南京",
    income: "退休金",
    category: "银发新青年",
    lifestyle: "退休生活，广场舞爱好者，关注健康",
    painPoints: "膝关节不适，血糖偏高风险，精力不足",
    needs: "保护关节，辅助控糖，提升精力",
    scenes: "广场舞前后、午后休息、家庭聚会",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_广场舞爱好者",
    targetAudience: "55-65岁退休女性",
    preferredProducts: ["湿祛轻畅草本定制茶饮", "补气焕活草本定制茶饮"],
    catchphrases: ["广场舞姐妹推荐", "老伴也说好", "喝了三个月了"],
    timeSlots: ["07:00-08:00", "14:30-15:30", "20:00-21:00"],
    xhsRatio: 0.2,
  },
  {
    name: "吴建军",
    nickname: "建军叔的健康路",
    gender: "male",
    age: 57,
    occupation: "个体经营者",
    city: "杭州",
    income: "经营收入",
    category: "银发新青年",
    lifestyle: "经营小生意，注重身体，关注中医养生",
    painPoints: "经营压力大，肠胃不好，精力透支",
    needs: "调理肠胃，补充元气，缓解压力",
    scenes: "开店前、午休、关店后",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_个体经营",
    targetAudience: "50-60岁个体经营者",
    preferredProducts: ["补气焕活草本定制茶饮", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["做生意的养生之道", "确实感觉精神了", "老伴也爱喝"],
    timeSlots: ["08:30-09:30", "13:00-14:00", "21:00-22:00"],
    xhsRatio: 0.2,
  },
  {
    name: "赵美华",
    nickname: "美华阿姨的生活",
    gender: "female",
    age: 54,
    occupation: "社区工作者",
    city: "北京",
    income: "工资+补贴",
    category: "银发新青年",
    lifestyle: "社区工作，人际关系广，喜欢分享",
    painPoints: "工作繁忙，腰腿不适，免疫力下降",
    needs: "增强免疫力，缓解腰腿不适，提升精力",
    scenes: "社区活动、工作间隙、家庭聚会",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_社区工作者",
    targetAudience: "50-60岁社区工作者",
    preferredProducts: ["补气焕活草本定制茶饮", "红颜透润草本定制茶饮"],
    catchphrases: ["社区姐妹们都在喝", "老伴也说好", "确实有效果"],
    timeSlots: ["08:00-09:00", "12:00-13:00", "20:30-21:30"],
    xhsRatio: 0.25,
  },
  {
    name: "孙长贵",
    nickname: "长贵爷爷的养生经",
    gender: "male",
    age: 63,
    occupation: "退休干部",
    city: "上海",
    income: "退休金",
    category: "银发新青年",
    lifestyle: "退休后学习健康知识，关注中医文化",
    painPoints: "心脑血管风险，精力不足，记忆力下降",
    needs: "辅助心脑血管健康，提升记忆力，延缓衰老",
    scenes: "早晨锻炼、读书时、家庭聚餐",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_退休干部",
    targetAudience: "58-68岁退休干部",
    preferredProducts: ["补气焕活草本定制茶饮", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["老同志的养生选择", "喝了三个月了", "确实感觉精神了"],
    timeSlots: ["07:30-08:30", "14:00-15:00", "20:00-21:00"],
    xhsRatio: 0.15,
  },
  {
    name: "钱淑珍",
    nickname: "淑珍奶奶的健康秘诀",
    gender: "female",
    age: 61,
    occupation: "退休护士",
    city: "广州",
    income: "退休金",
    category: "银发新青年",
    lifestyle: "退休护士，科学养生，关注慢病管理",
    painPoints: "慢性疲劳，骨质疏松，睡眠质量差",
    needs: "改善慢性疲劳，补充钙质，改善睡眠",
    scenes: "早晨锻炼、午后休息、晚间养生",
    language: "老伴也说好，确实感觉精神了，喝了三个月了",
    platform: "wechat",
    personaName: "银发新青年_退休护士",
    targetAudience: "55-65岁退休医护人员",
    preferredProducts: ["补气焕活草本定制茶饮", "红颜透润草本定制茶饮"],
    catchphrases: ["护士的养生选择", "科学调理", "全家都在喝"],
    timeSlots: ["08:00-09:00", "14:00-15:00", "20:30-21:30"],
    xhsRatio: 0.2,
  },
];

// 智慧养生人群（10人）
const CUSTOMERS_ZHIHUI = [
  {
    name: "方晨曦",
    nickname: "晨曦聊药食同源",
    gender: "female",
    age: 28,
    occupation: "中医学研究生",
    city: "北京",
    income: "奖学金+兼职",
    category: "智慧养生",
    lifestyle: "研究中医理论，注重科学验证，喜欢科普",
    painPoints: "学业压力大，需要科学管理身体状态",
    needs: "科学养生，验证中医理论，分享专业知识",
    scenes: "实验室间隙、早晨打卡、科普内容创作",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_中医研究生",
    targetAudience: "22-35岁有中医知识背景的年轻人",
    preferredProducts: ["补气焕活草本定制茶饮", "清脂纤纤草本定制茶饮"],
    catchphrases: ["今天聊聊药食同源", "成分党来扒一扒", "科学养生不玄学"],
    timeSlots: ["08:00-09:00", "12:30-13:30", "22:00-23:00"],
    xhsRatio: 0.9,
  },
  {
    name: "李博文",
    nickname: "博文的养生实验室",
    gender: "male",
    age: 32,
    occupation: "生物医学工程师",
    city: "上海",
    income: "20k-35k",
    category: "智慧养生",
    lifestyle: "理工科思维，用数据验证养生效果",
    painPoints: "工作压力大，需要科学方法管理健康",
    needs: "数据驱动的养生方案，科学验证效果",
    scenes: "实验室、早晨打卡、数据记录",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_生物工程师",
    targetAudience: "25-38岁理工科背景的养生爱好者",
    preferredProducts: ["湿祛轻畅草本定制茶饮", "悦活草本美式"],
    catchphrases: ["用数据说话", "成分党必看", "科学养生不玄学"],
    timeSlots: ["07:30-08:30", "12:00-13:00", "22:00-23:00"],
    xhsRatio: 0.9,
  },
  {
    name: "陈雅文",
    nickname: "雅文的本草笔记",
    gender: "female",
    age: 26,
    occupation: "中药学本科生",
    city: "成都",
    income: "奖学金",
    category: "智慧养生",
    lifestyle: "学习中药知识，关注药食同源，喜欢科普",
    painPoints: "学业繁重，需要调节身心状态",
    needs: "科学运用中药知识，调理身体，分享学习",
    scenes: "课间休息、图书馆、科普创作",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_中药学生",
    targetAudience: "20-30岁中医药专业学生",
    preferredProducts: ["补气焕活草本定制茶饮", "红颜透润草本定制茶饮"],
    catchphrases: ["本草科普时间", "药食同源小课堂", "成分党来扒一扒"],
    timeSlots: ["09:00-10:00", "14:00-15:00", "21:30-22:30"],
    xhsRatio: 0.95,
  },
  {
    name: "王思远",
    nickname: "思远的健康实验",
    gender: "male",
    age: 30,
    occupation: "健康科技创业者",
    city: "深圳",
    income: "创业收入",
    category: "智慧养生",
    lifestyle: "关注健康科技，结合传统与现代，创业中",
    painPoints: "创业压力大，需要高效的健康管理方案",
    needs: "高效养生，科技赋能传统，分享创新",
    scenes: "创业办公室、产品测试、内容创作",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_健康科技创业者",
    targetAudience: "25-35岁健康科技从业者",
    preferredProducts: ["悦活草本美式", "悦纤草本美式"],
    catchphrases: ["传统+科技的养生新方式", "成分党必看", "科学养生不玄学"],
    timeSlots: ["07:00-08:00", "12:00-13:00", "22:30-23:30"],
    xhsRatio: 0.9,
  },
  {
    name: "刘晓华",
    nickname: "晓华的养生科普",
    gender: "female",
    age: 35,
    occupation: "健康类KOL",
    city: "北京",
    income: "内容创作收入",
    category: "智慧养生",
    lifestyle: "专职内容创作，深度研究健康话题",
    painPoints: "需要持续输出高质量内容，保持专业性",
    needs: "深度了解产品，科学验证，专业内容创作",
    scenes: "内容创作、产品测评、粉丝互动",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_健康KOL",
    targetAudience: "25-40岁关注健康的内容消费者",
    preferredProducts: ["补气焕活草本定制茶饮", "红颜透润草本定制茶饮", "悦颜草本美式"],
    catchphrases: ["今天聊聊药食同源", "深度测评来了", "科学养生不玄学"],
    timeSlots: ["09:00-10:00", "15:00-16:00", "21:00-22:00"],
    xhsRatio: 0.95,
  },
  {
    name: "张明轩",
    nickname: "明轩的中医日记",
    gender: "male",
    age: 38,
    occupation: "中医诊所医生",
    city: "杭州",
    income: "15k-25k",
    category: "智慧养生",
    lifestyle: "中医从业者，注重传统文化传承，喜欢科普",
    painPoints: "工作繁忙，需要高效的个人养生方案",
    needs: "科学验证中医理论，分享专业知识，个人养生",
    scenes: "诊间休息、科普创作、患者教育",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_中医医生",
    targetAudience: "25-45岁中医爱好者",
    preferredProducts: ["补气焕活草本定制茶饮", "湿祛轻畅草本定制茶饮"],
    catchphrases: ["中医医生的日常选择", "药食同源科普", "科学养生不玄学"],
    timeSlots: ["08:30-09:30", "12:30-13:30", "21:00-22:00"],
    xhsRatio: 0.85,
  },
  {
    name: "吴雨桐",
    nickname: "雨桐的草本研究",
    gender: "female",
    age: 24,
    occupation: "食品科学研究生",
    city: "广州",
    income: "奖学金",
    category: "智慧养生",
    lifestyle: "研究食品成分，关注功能性食品，喜欢分享",
    painPoints: "实验室工作压力大，需要科学调理",
    needs: "科学验证成分，了解功能性食品，分享研究",
    scenes: "实验室、学术交流、内容创作",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_食品科学研究生",
    targetAudience: "20-30岁食品科学爱好者",
    preferredProducts: ["清脂纤纤草本定制茶饮", "悦纤草本美式"],
    catchphrases: ["成分党来扒一扒", "食品科学视角", "科学养生不玄学"],
    timeSlots: ["09:00-10:00", "13:00-14:00", "22:00-23:00"],
    xhsRatio: 0.9,
  },
  {
    name: "赵健康",
    nickname: "健康哥的养生经",
    gender: "male",
    age: 42,
    occupation: "健康管理师",
    city: "上海",
    income: "15k-25k",
    category: "智慧养生",
    lifestyle: "专业健康管理，结合中西医理论，科学养生",
    painPoints: "需要持续学习新知识，保持专业竞争力",
    needs: "深度了解产品，科学评估效果，专业推荐",
    scenes: "客户咨询、内容创作、专业学习",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_健康管理师",
    targetAudience: "30-50岁注重科学养生的人群",
    preferredProducts: ["补气焕活草本定制茶饮", "湿祛轻畅草本定制茶饮", "悦活草本美式"],
    catchphrases: ["健康管理师的专业推荐", "成分党必看", "科学养生不玄学"],
    timeSlots: ["08:00-09:00", "12:00-13:00", "21:30-22:30"],
    xhsRatio: 0.9,
  },
  {
    name: "孙文静",
    nickname: "文静的养生实验室",
    gender: "female",
    age: 29,
    occupation: "营养学讲师",
    city: "武汉",
    income: "10k-18k",
    category: "智慧养生",
    lifestyle: "教学与研究并重，关注营养科学，喜欢科普",
    painPoints: "教学工作繁忙，需要高效的个人养生",
    needs: "科学验证营养价值，分享专业知识，个人调理",
    scenes: "课前准备、科普创作、学生互动",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_营养学讲师",
    targetAudience: "22-35岁营养学爱好者",
    preferredProducts: ["红颜透润草本定制茶饮", "清脂纤纤草本定制茶饮"],
    catchphrases: ["营养学讲师的日常", "成分党来扒一扒", "科学养生不玄学"],
    timeSlots: ["08:30-09:30", "12:00-13:00", "21:00-22:00"],
    xhsRatio: 0.9,
  },
  {
    name: "周天宇",
    nickname: "天宇的健康哲学",
    gender: "male",
    age: 33,
    occupation: "哲学系讲师",
    city: "南京",
    income: "10k-16k",
    category: "智慧养生",
    lifestyle: "人文思维，关注身心整体健康，喜欢深度思考",
    painPoints: "脑力劳动过度，需要身心平衡的养生方案",
    needs: "身心整体调理，哲学视角的养生，深度思考",
    scenes: "备课间隙、阅读时、晨间冥想",
    language: "今天聊聊药食同源，成分党来扒一扒，科学养生不玄学",
    platform: "xiaohongshu",
    personaName: "智慧养生_人文学者",
    targetAudience: "25-40岁人文社科背景的养生爱好者",
    preferredProducts: ["补气焕活草本定制茶饮", "悦活草本美式"],
    catchphrases: ["身心合一的养生哲学", "药食同源的文化内涵", "科学养生不玄学"],
    timeSlots: ["07:30-08:30", "12:30-13:30", "22:00-23:00"],
    xhsRatio: 0.85,
  },
];

// 合并所有客户
const ALL_CUSTOMERS = [
  ...CUSTOMERS_BAILING,
  ...CUSTOMERS_MAMA,
  ...CUSTOMERS_JIANKANG,
  ...CUSTOMERS_YINFA,
  ...CUSTOMERS_ZHIHUI,
];

// ─────────────────────────────────────────────
// 3. 素材数据（30条）
// ─────────────────────────────────────────────
const MATERIALS_DATA = [
  // ink_bg (10条)
  { filename: "ink_bg_001.jpg", productLine: "草本茶饮", productName: "清脂纤纤草本定制茶饮", sceneType: "ink_bg", tags: "水墨,清新,绿色,茶饮", styleTags: { style: "ink", color: "green", mood: "fresh" } },
  { filename: "ink_bg_002.jpg", productLine: "草本茶饮", productName: "补气焕活草本定制茶饮", sceneType: "ink_bg", tags: "水墨,温暖,红色,补气", styleTags: { style: "ink", color: "warm_red", mood: "energetic" } },
  { filename: "ink_bg_003.jpg", productLine: "草本茶饮", productName: "湿祛轻畅草本定制茶饮", sceneType: "ink_bg", tags: "水墨,轻盈,蓝色,祛湿", styleTags: { style: "ink", color: "blue", mood: "light" } },
  { filename: "ink_bg_004.jpg", productLine: "草本茶饮", productName: "红颜透润草本定制茶饮", sceneType: "ink_bg", tags: "水墨,粉色,玫瑰,养颜", styleTags: { style: "ink", color: "pink", mood: "elegant" } },
  { filename: "ink_bg_005.jpg", productLine: "草本咖啡", productName: "悦纤草本美式", sceneType: "ink_bg", tags: "水墨,咖啡,深棕,提神", styleTags: { style: "ink", color: "brown", mood: "focused" } },
  { filename: "ink_bg_006.jpg", productLine: "草本咖啡", productName: "悦活草本美式", sceneType: "ink_bg", tags: "水墨,活力,橙色,元气", styleTags: { style: "ink", color: "orange", mood: "vibrant" } },
  { filename: "ink_bg_007.jpg", productLine: "草本咖啡", productName: "悦轻草本美式", sceneType: "ink_bg", tags: "水墨,轻盈,浅棕,畅达", styleTags: { style: "ink", color: "light_brown", mood: "relaxed" } },
  { filename: "ink_bg_008.jpg", productLine: "草本咖啡", productName: "悦颜草本美式", sceneType: "ink_bg", tags: "水墨,颜值,玫瑰金,职场", styleTags: { style: "ink", color: "rose_gold", mood: "professional" } },
  { filename: "ink_bg_009.jpg", productLine: "通用", productName: "灵芝水铺", sceneType: "ink_bg", tags: "水墨,灵芝,传统,养生", styleTags: { style: "ink", color: "earth", mood: "traditional" } },
  { filename: "ink_bg_010.jpg", productLine: "通用", productName: "灵芝水铺", sceneType: "ink_bg", tags: "水墨,简约,白色,纯净", styleTags: { style: "ink", color: "white", mood: "pure" } },
  // seasonal (8条)
  { filename: "seasonal_spring_001.jpg", productLine: "草本茶饮", productName: "清脂纤纤草本定制茶饮", sceneType: "seasonal", tags: "春季,排湿,绿色,清新", styleTags: { season: "spring", theme: "detox" }, season: "spring" },
  { filename: "seasonal_spring_002.jpg", productLine: "草本茶饮", productName: "红颜透润草本定制茶饮", sceneType: "seasonal", tags: "春季,养颜,花朵,粉色", styleTags: { season: "spring", theme: "beauty" }, season: "spring" },
  { filename: "seasonal_summer_001.jpg", productLine: "草本咖啡", productName: "悦纤草本美式", sceneType: "seasonal", tags: "夏季,清爽,冰镇,消暑", styleTags: { season: "summer", theme: "cool" }, season: "summer" },
  { filename: "seasonal_summer_002.jpg", productLine: "草本茶饮", productName: "湿祛轻畅草本定制茶饮", sceneType: "seasonal", tags: "夏季,祛湿,清凉,轻盈", styleTags: { season: "summer", theme: "light" }, season: "summer" },
  { filename: "seasonal_autumn_001.jpg", productLine: "草本茶饮", productName: "补气焕活草本定制茶饮", sceneType: "seasonal", tags: "秋季,补气,金色,收获", styleTags: { season: "autumn", theme: "nourish" }, season: "autumn" },
  { filename: "seasonal_autumn_002.jpg", productLine: "草本咖啡", productName: "悦活草本美式", sceneType: "seasonal", tags: "秋季,活力,暖色,元气", styleTags: { season: "autumn", theme: "energy" }, season: "autumn" },
  { filename: "seasonal_winter_001.jpg", productLine: "草本茶饮", productName: "补气焕活草本定制茶饮", sceneType: "seasonal", tags: "冬季,温补,暖意,红色", styleTags: { season: "winter", theme: "warm" }, season: "winter" },
  { filename: "seasonal_winter_002.jpg", productLine: "草本咖啡", productName: "悦颜草本美式", sceneType: "seasonal", tags: "冬季,暖心,颜值,职场", styleTags: { season: "winter", theme: "cozy" }, season: "winter" },
  // scene (7条)
  { filename: "scene_office_001.jpg", productLine: "草本咖啡", productName: "悦活草本美式", sceneType: "scene", tags: "办公室,白领,下午茶,工作", styleTags: { scene: "office", mood: "productive" } },
  { filename: "scene_office_002.jpg", productLine: "草本咖啡", productName: "悦颜草本美式", sceneType: "scene", tags: "办公室,女性,职场,精致", styleTags: { scene: "office", mood: "elegant" } },
  { filename: "scene_gym_001.jpg", productLine: "草本茶饮", productName: "清脂纤纤草本定制茶饮", sceneType: "scene", tags: "健身房,运动,减脂,活力", styleTags: { scene: "gym", mood: "energetic" } },
  { filename: "scene_home_001.jpg", productLine: "草本茶饮", productName: "红颜透润草本定制茶饮", sceneType: "scene", tags: "家居,温馨,妈妈,护肤", styleTags: { scene: "home", mood: "cozy" } },
  { filename: "scene_outdoor_001.jpg", productLine: "草本咖啡", productName: "悦轻草本美式", sceneType: "scene", tags: "户外,自然,轻盈,清新", styleTags: { scene: "outdoor", mood: "free" } },
  { filename: "scene_cafe_001.jpg", productLine: "草本咖啡", productName: "悦纤草本美式", sceneType: "scene", tags: "咖啡馆,文艺,打卡,分享", styleTags: { scene: "cafe", mood: "artistic" } },
  { filename: "scene_morning_001.jpg", productLine: "通用", productName: "灵芝水铺", sceneType: "scene", tags: "早晨,阳光,开始,仪式感", styleTags: { scene: "morning", mood: "ritual" } },
  // decoration (5条)
  { filename: "deco_herbs_001.jpg", productLine: "通用", productName: "灵芝水铺", sceneType: "decoration", tags: "草本,食材,药材,天然", styleTags: { type: "herbs", style: "flat_lay" } },
  { filename: "deco_lingzhi_001.jpg", productLine: "通用", productName: "灵芝水铺", sceneType: "decoration", tags: "灵芝,主角,品牌,核心", styleTags: { type: "main_ingredient", style: "hero_shot" } },
  { filename: "deco_pattern_001.jpg", productLine: "通用", productName: "灵芝水铺", sceneType: "decoration", tags: "花纹,装饰,中式,传统", styleTags: { type: "pattern", style: "traditional_chinese" } },
  { filename: "deco_texture_001.jpg", productLine: "通用", productName: "灵芝水铺", sceneType: "decoration", tags: "纹理,质感,高端,品质", styleTags: { type: "texture", style: "premium" } },
  { filename: "deco_logo_001.jpg", productLine: "通用", productName: "灵芝水铺", sceneType: "decoration", tags: "品牌,LOGO,标识,灵芝", styleTags: { type: "branding", style: "logo" } },
];

// ─────────────────────────────────────────────
// 主函数
// ─────────────────────────────────────────────
async function main() {
  console.log("🌿 灵芝水铺 — 开始写入测试数据...\n");

  // 检查是否已有数据
  const existingCustomers = await prisma.customer.count();
  if (existingCustomers > 0) {
    console.log(`⚠️  数据库中已有 ${existingCustomers} 个客户，跳过种子数据写入。`);
    console.log("   如需重新写入，请先清空数据库。");
    return;
  }

  // ── 写入产品（Prompt 表）──
  console.log("📦 写入 8 款产品...");
  for (const product of PRODUCTS) {
    await prisma.prompt.upsert({
      where: { key: product.key },
      update: {},
      create: product,
    });
  }
  console.log(`   ✅ 产品写入完成 (${PRODUCTS.length} 款)\n`);

  // ── 写入客户 ──
  console.log("👥 写入 50 个客户（含关联表）...");
  let customerCount = 0;
  for (const c of ALL_CUSTOMERS) {
    const xhsRatio = c.xhsRatio ?? 0.5;
    const platform = xhsRatio >= 0.5 ? "xiaohongshu" : "wechat";

    const customer = await prisma.customer.create({
      data: {
        name: c.name,
        nickname: c.nickname,
        gender: c.gender,
        age: c.age,
        occupation: c.occupation,
        city: c.city,
        income: c.income,
        category: c.category,
        lifestyle: c.lifestyle,
        painPoints: c.painPoints,
        needs: c.needs,
        scenes: c.scenes,
        language: c.language,
        platform: platform,
        personaName: c.personaName,
        targetAudience: c.targetAudience,
        status: "active",
        tier3Eligible: false,
      },
    });

    // PublishHabit
    await prisma.publishHabit.create({
      data: {
        customerId: customer.id,
        preferredTimeSlots: c.timeSlots,
        dailyPostCount: Math.floor(Math.random() * 3) + 2,
        imageTextRatio: xhsRatio,
        contentLengthPref: xhsRatio >= 0.7 ? "long" : "medium",
        hashtagStyle: "mixed",
      },
    });

    // ContentPreference
    await prisma.contentPreference.create({
      data: {
        customerId: customer.id,
        preferredProducts: c.preferredProducts,
        topicTags: c.catchphrases,
        avoidTopics: ["医疗声称", "治疗", "治愈", "疾病"],
        seasonalFocus: true,
      },
    });

    // WritingStyle
    await prisma.writingStyle.create({
      data: {
        customerId: customer.id,
        tone: c.category === "精致妈妈" ? "warm" : c.category === "智慧养生" ? "professional" : "casual",
        catchphrases: c.catchphrases,
        emojiFrequency: xhsRatio >= 0.7 ? "high" : "medium",
      },
    });

    // TrendTracking
    await prisma.trendTracking.create({
      data: {
        customerId: customer.id,
        industryKeywords: ["药食同源", "灵芝", "草本养生", "功能性饮品"],
        seasonalTopics: ["春季排湿", "夏季消暑", "秋季补气", "冬季温补"],
        trendingResponse: "moderate",
      },
    });

    // PerformanceMetric
    await prisma.performanceMetric.create({
      data: {
        customerId: customer.id,
        avgLikeRate: Math.random() * 0.05 + 0.02,
        avgCommentRate: Math.random() * 0.02 + 0.005,
        avgShareRate: Math.random() * 0.01 + 0.002,
        totalPosts: Math.floor(Math.random() * 50) + 10,
        viralCount: Math.floor(Math.random() * 3),
      },
    });

    customerCount++;
    if (customerCount % 10 === 0) {
      console.log(`   进度: ${customerCount}/50`);
    }
  }
  console.log(`   ✅ 客户写入完成 (${customerCount} 人)\n`);

  // ── 写入素材 ──
  console.log("🖼️  写入 30 条模拟素材...");
  for (const m of MATERIALS_DATA) {
    await prisma.material.create({
      data: {
        filename: m.filename,
        filepath: `/materials/system/${m.filename}`,
        webPath: `/api/materials/system/${m.filename}`,
        productLine: m.productLine,
        productName: m.productName,
        sceneType: m.sceneType,
        tags: m.tags,
        styleTags: m.styleTags,
        tierLevel: 2,
        sourceType: "system_a_push",
        season: (m as any).season ?? null,
        status: "active",
        isFormula: false,
        isProduct: false,
      },
    });
  }
  console.log(`   ✅ 素材写入完成 (${MATERIALS_DATA.length} 条)\n`);

  // ── 汇总 ──
  const finalCustomers = await prisma.customer.count();
  const finalMaterials = await prisma.material.count();
  const finalProducts = await prisma.prompt.count({ where: { category: "product" } });

  console.log("═══════════════════════════════════════");
  console.log("🎉 测试数据写入完成！");
  console.log(`   客户总数：${finalCustomers} 人`);
  console.log(`   素材总数：${finalMaterials} 条`);
  console.log(`   产品总数：${finalProducts} 款`);
  console.log("═══════════════════════════════════════");
}

main()
  .catch((e) => {
    console.error("❌ 种子数据写入失败：", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
